pub mod binary_search;
pub mod closest_point;
pub mod counting_inversions;
pub mod major_element;
pub mod merge_sort;
pub mod merge_sort_for_closest_point;
pub mod organizing_lottery;
pub mod quick_sort;
pub mod struct_defs;
